### ISSUE TITLE
[QUESTION] 0 credits for completion

### ISSUE THREAD

**Issue by Linguistie** [SaengerItsWar/shavit-credits#6]
[Timer] You have earned 0 credits for finishing this map.
[Timer] You have earned 0 credits for breaking the WR.
[Timer] You have earned 0 credits for finishing this map again.
[Timer] You have earned 0 credits for breaking your Personal Best again.
[Timer] You have earned 0 credits for breaking the WR again.

Is there any .cfg file to configure that?

Didn't find anything related to shavit-credits in
_csgo\cfg\sourcemod_
or
_csgo\addons\sourcemod\configs_

**Comment by SaengerItsWar** [comment]
Did you load the plugin manual or over a server restart?
the config can be found in csgo/cfg/sourcemod/Shavit-credits.cfg

**Comment by Linguistie** [comment]
I don't know how to do that manually, so yes, over a server restart. 
I can see the .cfg after doing another restart, thanks. Will look through the .cfg and restart the server again and try it out.

**Comment by SaengerItsWar** [comment]
You don't need to restart a simple map change does it also

**Comment by Linguistie** [comment]
I looked through the .cfg, I assume the issue was in that I had _credits_enable_t1_  set to "1" by default, so it felt like it was broken. It is working fine now, appreciate it! I think setting it to 1 by default would bring less confusion and fewer questions like that, if any. 

Also, mild localization error in // Enable Store credits given for greaking the map Record? (breaking)

**Comment by SaengerItsWar** [comment]
I must say that credits_enable_t1 is one by default cause only the normal map finishes will be ignored anything else will go through.
