### ISSUE TITLE
[QUESTION] Does this plugin support R1KO's shop?

### ISSUE THREAD

**Issue by Linguistie** [SaengerItsWar/shavit-credits#7]
Will any of the plugin versions work with this https://github.com/FD-Forks/Shop-Core ?

**Comment by Linguistie** [comment]
If not, it would be great if you could adapt it to this one, too

**Comment by SaengerItsWar** [comment]
i can do this.

**Comment by SaengerItsWar** [comment]
I added the support for R1ko's Shop.
I'm going to close this for now but if something is wrong just reopen it or open a new one if you want.
